config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  get 'recipes/new'
  get 'recipes/edit'
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  get 'home/index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  root to: "home#index"
  resources :users
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  attachment :image

  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  attachment :profile_bg_image
  has_many :recipes, dependent: :destroy

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.order(created_at: "DESC").limit(12)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = @recipe.user
  end

  def new
    @recipe = Recipe.new
    render layout: 'no_footer'
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: '投稿に成功しました'
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path, alart: '不正なアクセスです'
    end
    render layout: 'no_footer'
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: '更新に成功しました'
    else
      render :edit
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to user_path(recipe.user)
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :profile, :body, :image)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  layout 'no_footer'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  layout 'no_footer'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @recipe = @user.recipes.page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alart: '不正なアクセスです'
    end
    render layout: 'no_footer'
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: '更新に成功しました'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image, :profile_bg_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = '楽楽レシピ'
    if page_title.empty?
      base_title
    else
      page_title + " - " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="main-head p-relative">
  <div class="home__title">料理を楽しくラクして作ろう</div>
  <figure class="main-visual">
    <%= image_tag "home-image.jpg", class: "main-visual__img" %>
  </figure>
  <% if !current_user %>
  <div class="signup-btn">
    <%= link_to "新規登録", new_user_registration_path, class: "btn btn--signup signup-btn__customize" %>
  </div>
  <% end %>
</div>
<div class="global-container">
  <div class="home-index-container card--col">
    <h1 class="main__title">新着レシピ12選</h1>
    <% @recipes.each do |recipe|%>
      <div class="card">
        <%= link_to recipe_path(recipe), class: "link--no-decorate link--hover-gray" do %>
          <figure class="card__img-wrapper">
              <%= attachment_image_tag recipe, :image, class: "card__img", fallback: "no-image-recipe.jpg" %>
          </figure>
          <div class="card__body">
            <h2 class="card__title"><%= recipe.title %></h2>
            <p class="card__text"><%= recipe.profile %></p>

            <object>
              <%= link_to user_path(recipe.user), class: "link--no-decorate" do %>
                <div class="user-item-sm mb-xs">
                  <figure class="user-item-sm__icon-wrapper">
                    <%= attachment_image_tag recipe.user, :profile_image, class: "user-item-sm__icon", fallback: "no-image-profile.png" %>
                  </figure>
                  <div class="user-item-sm__name"><%= recipe.user.username %></div>
                </div>
              <% end %>
            </object>
            
            <div class="posted-date">
              <div class="posted-date__title">投稿</div>
              <div class="posted-date__text"><%= recipe.updated_at.strftime("%Y年%m月%d日 %H:%M") %></div>
            </div>
            <hr>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="notication is-info">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notication is-danger">
    <p class="alert"><%= alert %></p>
  </div>
<% end %> 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer__inner">
    <figure class="logo">
      <%= image_tag "rakurecipe-logo.png", class: "logo__img" %>
    </figure>
    <div class="footer__title">
      料理を楽しくラクに作ろう
    </div>
    <nav class="footer__nav">
      <ul class="footer-menu">
        <li class="footer-menu__item">
          <%= link_to "ホーム", root_path, class: "footer-menu__link" %>
        </li>
        <li class="footer-menu__item">
          <%= link_to "レシピ一覧", recipes_path, class: "footer-menu__link" %>
        </li>
        <li class="footer-menu__item">
          <%= link_to "ユーザー一覧", users_path, class: "footer-menu__link" %>
        </li>
      </ul>
      <div class="footer__copyright">
        &copy; Rakurecipe
      </div>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg navbar-light bg-yellow p-none header__height fixed-top">
    <div class="container-fluid">
      <%= link_to  root_path, class: "navbar-brand" do %>
        <div class="logo">
          <%= image_tag "rakurecipe-logo.png", class: "logo__img" %>
          <div class="logo__title">楽楽レシピ</div>
        </div>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-flex-end-992up" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="ham-menu__item nav-item">
            <%= link_to root_path, class: "ham-menu__link nav-link" do %>
              <div class="ham-menu__link-inner">
                <div class="ham-menu__title">ホーム</div>
                <span><i class="fas fa-chevron-right"></i></span>
              </div>
            <% end %>
          </li>
          <li class="ham-menu__item nav-item">
            <%= link_to recipes_path, class: "ham-menu__link nav-link" do %>
              <div class="ham-menu__link-inner">
                <div class="ham-menu__title">レシピ一覧</div>
                <span><i class="fas fa-chevron-right"></i></span>
              </div>
            <% end %>
          </li>
          <li class="ham-menu__item nav-item">
            <%= link_to users_path, class: "ham-menu__link nav-link" do %>
              <div class="ham-menu__link-inner">
                <div class="ham-menu__title">ユーザー一覧</div>
                <span><i class="fas fa-chevron-right"></i></span>
              </div>
            <% end %>
          </li>

          <% if user_signed_in? %>
            <li class="ham-menu__item nav-item">
              <%= link_to user_path(current_user), class: "ham-menu__link nav-link" do %>
                <div class="ham-menu__link-inner">
                  <div class="ham-menu__title">マイページ</div>
                  <span><i class="fas fa-chevron-right"></i></span>
                </div>
              <% end %>
            </li>
            <li class="ham-menu__item nav-item">
              <%= link_to new_recipe_path, class: "ham-menu__link nav-link" do %>
                <div class="ham-menu__link-inner">
                  <div class="ham-menu__title">レシピ投稿</div>
                  <span><i class="fas fa-chevron-right"></i></span>
                </div>
              <% end %>
            </li>
            <li class="ham-menu__item nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "ham-menu__link nav-link" do %>
                <div class="ham-menu__link-inner">
                  <div class="ham-menu__title">ログアウト</div>
                  <span><i class="fas fa-chevron-right"></i></span>
                </div>
              <% end %>
            </li>
          <% else %>
            <li class="ham-menu__item nav-item">
              <%= link_to new_user_registration_path, class: "ham-menu__link nav-link" do %>
                <div class="ham-menu__link-inner">
                  <div class="ham-menu__title">新規登録</div>
                  <span><i class="fas fa-chevron-right"></i></span>
                </div>
              <% end %>
            </li>
            <li class="ham-menu__item nav-item">
              <%= link_to new_user_session_path, class: "ham-menu__link nav-link" do %>
                <div class="ham-menu__link-inner">
                  <div class="ham-menu__title">ログイン</div>
                  <span><i class="fas fa-chevron-right"></i></span>
                </div>
              <% end %>
            </li>
          <% end %>
          
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'apple-touch-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' %>
    <%= favicon_link_tag 'android-chrome-192x192.png', rel: 'android-touch-icon', sizes: '192x192', type: 'image/png' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Otomanopee+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="main pt-header-height">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/no_footer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'apple-touch-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' %>
    <%= favicon_link_tag 'android-chrome-192x192.png', rel: 'android-touch-icon', sizes: '192x192', type: 'image/png' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Otomanopee+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="main pt-header-height">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recipes/edit.html.erb
<% provide(:title, "レシピ編集") %>

<div class="global-container">
  <h1 class="main__title pt-sm">レシピ編集</h1>

  <%= render 'shared/error_messages' %>
  <%= form_with model: @recipe, local: true, class: "form" do |f| %>
    <div class="form__inner">
      <%= f.label :title, "レシピ名", class: "form__label" %>
      <%= f.text_field :title, class: "form__input" %>
    </div>
    <div class="form__inner">
      <%= f.label :profile, "レシピ紹介文", class: "form__label" %>
      <%= f.text_area :profile, class: "form__textarea form__textarea--md", placeholder: "例：昔ながらの家庭的なカレーが特徴です。" %>
    </div>
    <div class="form__inner">
      <%= f.label :body, "作り方", class: "form__label" %>
      <%= f.text_area :body, class: "form__textarea form__textarea--lr" %>
    </div>
    <div class="form__inner mb-lg">
      <%= f.label :image, "レシピ画像", class: "form__label" %>
      <%= f.attachment_field :image, class: "form__input" %>
    </div>
    <%= f.submit "更新する", class: "btn btn--submit" %>
  <% end %>
</div>

app/views/recipes/index.html.erb
<% provide(:title, "レシピ一覧") %>

<div class="global-container">
  <h1 class="main__title pt-sm">レシピ一覧</h1>
  <nav class="navbar navbar-light bg-light mb-10">
    <div class="container-fluid">
    <%= search_form_for @q, class: "d-flex" do |f| %>
      <%= f.search_field :title_cont, class: "form-control me-2", placeholder: "レシピ名" %>
      <%= f.submit '検索', class: "btn btn-outline-success" %>
    <% end %>
    </div>
  </nav>

  <% @recipes.each do |recipe|%>
    <%= link_to recipe_path(recipe), class: "link--no-decorate link--hover-gray" do %>
      <div class="media">
        <figure class="media__img-wrapper">
          <%= attachment_image_tag recipe, :image, class: "media__img", fallback: "no-image-recipe.jpg" %>
        </figure>
        <div class="media__body">
          <div class="media__body-head">
            <div class="media__title"><%= recipe.title %></div>
            <p class="media__text"><%= recipe.profile %></p>
          </div>
          <div class="media__body-foot">
            <object>
              <%= link_to user_path(recipe.user), class: "link--no-decorate" do %>
                <div class="user-item-xs mb-5">
                  <div class="user-item-xs__title">by</div>
                  <figure class="user-item-xs__icon-wrapper">
                    <%= attachment_image_tag recipe.user, :profile_image, class: "user-item-xs__icon", fallback: "no-image-profile.png" %>
                  </figure>
                  <div class="user-item-xs__text"><%= recipe.user.username %></div>
                </div>
               <% end %>
             </object>
            <div class="posted-date">
              <div class="posted-date__title font-sm">投稿</div>
              <div class="posted-date__text font-sm"><%= recipe.updated_at.strftime("%Y年%m月%d日 %H:%M") %></div>
            </div>
          </div>
        </div>
        </div>
      <% end %>
    <% end %>
    <%= paginate @recipes %>
  </div>

app/views/recipes/new.html.erb
<% provide(:title, "レシピ投稿") %>

<div class="global-container">
  <h1 class="main__title pt-sm">レシピ投稿</h1>

  <%= render 'shared/error_messages' %>
  <%= form_with model: @recipe, local: true, class: "form" do |f| %>
    <div class="form__inner">
      <%= f.label :title, "レシピ名", class: "form__label" %>
      <%= f.text_field :title, class: "form__input", placeholder: "例：カレーライス" %>
    </div>
    <div class="form__inner">
      <%= f.label :profile, "レシピ紹介文", class: "form__label" %>
      <%= f.text_area :profile, class: "form__textarea form__textarea--md", placeholder: "例：昔ながらの家庭的なカレーが特徴です。" %>
    </div>
    <div class="form__inner">
      <%= f.label :body, "作り方", class: "form__label" %>
      <%= f.text_area :body, class: "form__textarea form__textarea--lr" %>
    </div>
    <div class="form__inner mb-lg">
      <%= f.label :image, "レシピ画像", class: "form__label" %>
      <%= f.attachment_field :image, class: "form__input" %>
    </div>
    <%= f.submit "投稿する", class: "btn btn--submit" %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<% provide(:title, "レシピ詳細") %>

<div class="global-container">
  <h1 class="main__title pt-sm">レシピ詳細</h1>

  <div class="card-recipe">
    <div class="card-recipe__main-title"><%= @recipe.title %></div>
    <hr>
    <p class="card-recipe__profile"><%= simple_format @recipe.profile %></p>
    <figure class="card-recipe__img-wrapper">
      <%= attachment_image_tag @recipe, :image, class: "card-recipe__img", fallback: "no-image-recipe.jpg" %>
    </figure>
    <div class="card-recipe__heading">
      <div class="card-recipe__sub-title">作り方</div>
      <div class="posted-date">
        <div class="posted-date__title">投稿</div>
        <div class="posted-date__text"><%= @recipe.updated_at.strftime("%Y年%m月%d日 %H:%M") %></div>
      </div>
    </div>
    <hr class="mb-sm">
    <div class="card-recipe__content"><%= simple_format @recipe.body %></div>
    <div class="card-recipe__foot">
      <%= link_to user_path(@user) do %>
        <div class="user-item-lr">
          <figure class="user-item-lr__icon-wrapper">
            <%= attachment_image_tag @user, :profile_image, class: "user-item-lr__icon", fallback: "no-image-profile.png" %>
          </figure>
          <div class="user-item-lr__name"><%= @user.username %></div>
        </div>
      <% end %>
      <% if current_user && @user.id == current_user.id %>
        <div class="link">
          <%= link_to "編集", edit_recipe_path, class: "link__link" %>
          <%= link_to "削除", recipe_path(@recipe), method: :delete, data: {confirm: "削除しますか？"}, class: "link__link" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/shared/_error_messages.html.erb
<%# ユーザー情報エラー %>
<% if @user && @user.errors.any?%>
  <div id="error_explanation">
    <div class="alert">
      入力内容に<%= @user.errors.count %>個のエラーがあります。
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%# レシピ情報エラー %>
<% if @recipe && @recipe.errors.any?%>
  <div id="error_explanation">
    <div class="alert">
      入力内容に<%= @recipe.errors.count %>個のエラーがあります。
    </div>
    <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "ユーザー詳細") %>

<div class="global-container">
  <h1 class="main__title pt-sm">ユーザー詳細</h1>
  <div class="card-user">
    <div class="card-user__bg-icon-link">
      <figure class="card-user__bg-img-wrapper">
        <%= attachment_image_tag @user, :profile_bg_image, class: "card-user__bg-img", fallback: "no-image.jpg" %>
      </figure>

      <% if current_user && @user.id == current_user.id %>
        <div class="link link--card-user">
          <div class="link__outer">
            <%= link_to "編集", edit_user_path(@user), class: "link__link" %>
          </div>
        </div>
      <% end %>

      <figure class="card-user__icon-wrapper">
        <%= attachment_image_tag @user, :profile_image, class: "user-item-md__icon", fallback: "no-image-profile.png" %>
      </figure>
    </div>
    <div class="card-user__name"><%= @user.username %></div>
    <p class="card-user__profile"><%= @user.profile %></p>
    <hr>
  </div>

  <% @recipe.each do |recipe| %>
    <%= link_to recipe_path(recipe), class: "link--no-decorate link--hover-gray" do %>
      <div class="media">
        <figure class="media__img-wrapper">
          <%= attachment_image_tag recipe, :image, class: "media__img", fallback: "no-image-recipe.jpg" %>
        </figure>
        <div class="media__body">
          <div class="media__body-head">
            <div class="media__title"><%= recipe.title %></div>
            <p class="media__text"><%= recipe.profile %></p>
          </div>
          <div class="media__body-foot">
            <div class="media__body-foot">

              <% if current_user && @user.id == current_user.id %>
                <object>
                  <div class="link mb-5">
                    <%= link_to "編集", edit_recipe_path(recipe), class: "link__link" %>
                    <%= link_to "削除", recipe_path(recipe), method: :delete, data: {confirm: "削除しますか？"}, class: "link__link" %>
                  </div>
                </object>
              <% end %>

              <div class="posted-date">
                <div class="posted-date__title font-sm">投稿</div>
                <div class="posted-date__text font-sm"><%= recipe.updated_at.strftime("%Y年%m月%d日 %H:%M") %></div>
              </div>
            </div>
          </div>
        </div>
        </div>
      <% end %>
  <% end %>
  <%= paginate @recipe %>
</div>